import { Poppins } from "next/font/google"; // this is how we get fonts
import "./globals.css";

// components we do this to make it more organized
import Navbar from "./components/Navbar";

const poppins = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this component wraps all the children files which are page files.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
